/* ==================================================================
   stripe.ts — the Stripe half of billing, in one place

   THE ROUTE THIS TAKES, and it is a decision worth reading before
   changing anything here. BILLING-PLAN §6 mapped TWO ways for a Stripe
   subscription to become a tier:

     A. RevenueCat ingests it — Stripe's webhooks point at RevenueCat,
        the subscription is registered by POSTing to their receipts
        endpoint with `X-Platform: stripe`, and from then on it arrives
        as the same RevenueCat webhook the stores produce.
     B. Stripe's OWN webhook, HMAC-signed, feeding the same
        `applyEntitlement()`. Two sources, one writer.

   **B is what is built.** Every step of A is marked `[confirm every
   step]` in the plan because it rests on RevenueCat documentation this
   container cannot reach, and a build machine cannot close that gap —
   whereas B is verifiable end to end against Stripe test mode with the
   Stripe CLI and nothing else. The plan names B as the fallback for
   exactly this case. What B gives up is one dashboard showing every
   subscriber: a Stripe subscription will not appear in RevenueCat.
   That is the cost, and it is recoverable later — the receipts POST
   can be added beside this without moving the writer.

   NO SDK. Raw `fetch` against api.stripe.com with form encoding is
   about thirty lines and every one of them is inspectable and
   injectable; an SDK would be a dependency whose behaviour this
   container also cannot verify, wrapped around the same HTTP calls.
   The AI providers are called the same way, for the same reason.

   WHAT CANNOT BE VERIFIED FROM HERE, said plainly rather than implied
   by a green suite: Stripe's real event shapes, its real signature
   header, and whether a Checkout session created with these parameters
   is accepted. The signature scheme implemented below is the one
   RevenueCat's is modelled on and the two are byte-identical in shape
   — which is a reason to expect it to be right and NOT evidence that
   it is. BILLING-PLAN.md Phase 6 has the
   test-mode checklist.
   ================================================================== */

import { TIER_RANK, type BillingTier } from "./entitlement.ts";

const STRIPE_API = "https://api.stripe.com/v1";

/* PINNED, because an API version is exactly the kind of thing that
   changes underneath you and reshapes a response. Stripe defaults an
   unpinned request to whatever the account's dashboard is set to —
   a value nobody in this repository can see. Declared here rather than
   beside its use, because this project has a temporal-dead-zone bug in
   its history and a const read above its declaration reads wrong even
   where it is legal.

   WHERE A COMPLETED CHECKOUT RETURNS TO. Derived from nothing at
   runtime: taking it from the request's Origin header would be an open
   redirect with a signed-in session attached. It MIRRORS
   src/legalLinks.js's SITE_URL — a browser bundle and a Deno function
   cannot share a module — and a test asserts the two are equal. */
export const STRIPE_API_VERSION = "2024-06-20";
export const SITE_URL = "https://www.uniplannerapp.com";
export const CHECKOUT_SUCCESS_URL = `${SITE_URL}/?checkout=done`;
export const CHECKOUT_CANCEL_URL = `${SITE_URL}/?checkout=cancelled`;

/* THE SIX PRICES, keyed by a `lookup_key` WE choose on the Stripe Price.

   WHY NOT THE PRICE ID: `price_1A2b3C…` is generated by Stripe, so a
   table of them here would be a restatement of a dashboard with no
   source of truth in this repository — and the id differs between test
   mode and live mode, so the table would have to be right twice. A
   lookup key is a value we pick, identical in both modes, and it is
   the same shape as the RevenueCat package identifiers in
   src/purchasePlans.js — which a test asserts these agree with, so a
   tier or a duration renamed in one place goes red.

   AND THE CLIENT NEVER SENDS A PRICE. It asks for a tier and a
   duration; the server resolves which Price that is. A client that
   named the price could name a cheaper one — the same reasoning that
   makes the uid come from the JWT rather than the request body. */
export const STRIPE_LOOKUP_KEYS: Record<string, { tier: BillingTier; duration: string }> = {
  uniplanner_studyai_monthly: { tier: "ai", duration: "monthly" },
  uniplanner_studyai_sixmonth: { tier: "ai", duration: "sixmonth" },
  uniplanner_studyai_annual: { tier: "ai", duration: "annual" },
  uniplanner_studyaimax_monthly: { tier: "ai_max", duration: "monthly" },
  uniplanner_studyaimax_sixmonth: { tier: "ai_max", duration: "sixmonth" },
  uniplanner_studyaimax_annual: { tier: "ai_max", duration: "annual" },
};

/** The lookup key for a (tier, duration) pair, or null if it is not one we sell. */
export function lookupKeyFor(tier: string, duration: string): string | null {
  for (const [key, plan] of Object.entries(STRIPE_LOOKUP_KEYS)) {
    if (plan.tier === tier && plan.duration === duration) return key;
  }
  return null;
}

/* WHICH SUBSCRIPTION STATUSES COUNT AS ENTITLED, and the two awkward
   ones are the point of writing this down.

   `past_due` IS ENTITLED. Stripe is retrying the card; the App Store's
   billing grace period behaves the same way, and BILLING-PLAN already
   says the re-read design keeps a tier through it without any code
   knowing grace periods exist. Cutting somebody off on the first failed
   retry is a support ticket from a student whose bank declined once.

   `unpaid` IS NOT. That is Stripe having finished retrying.

   `trialing` IS, obviously, and `canceled` is not — but note that a
   subscription cancelled AT PERIOD END stays `active` until the period
   ends, so "they cancelled" does not remove access early. That matches
   what both stores do and what the refund section of BILLING-PLAN
   says. */
export const ENTITLED_STATUSES: readonly string[] = ["active", "trialing", "past_due"];

/* Every status Stripe documents today. It exists so that an UNKNOWN
   status — one added after this was written — is told apart from a
   known-and-not-entitled one. Reading a new status as "not entitled"
   would end the plan of everybody who happened to be in it. */
export const ALL_KNOWN_STATUSES: readonly string[] = [
  "active",
  "trialing",
  "past_due",
  "canceled",
  "unpaid",
  "incomplete",
  "incomplete_expired",
  "paused",
];

/**
 * The tier a Stripe SUBSCRIPTION implies — the whole decision, pure, so
 * the awkward cases are a table in a test rather than something only a
 * real Stripe account can answer.
 *
 * Takes a subscription object RE-READ from Stripe, never one lifted out
 * of a delivered webhook body. Same rule as `tierFromSubscriber`: the
 * payload is a trigger, the record is the truth.
 *
 * Returns `free` for anything not entitled, which is the right answer
 * for cancelled, unpaid, incomplete and never-subscribed alike — and is
 * what a `customer.subscription.deleted` event resolves to without any
 * code knowing what deletion means.
 *
 * **AND `recognised` IS THE ONE THAT MATTERS.** A subscription in an
 * entitled status whose items match NO lookup key we know is not a
 * student entitled to nothing — it is a question this function cannot
 * answer, and the two are catastrophically different in one direction:
 * a `lookup_key` missing from a response, or a price created in the
 * dashboard without one, would silently DOWNGRADE every paying Stripe
 * subscriber to free. That is the `fetchNote` rule pointed at money,
 * and the caller is required to refuse rather than write when this is
 * false.
 */
export function tierFromStripeSubscription(
  subscription: Record<string, unknown> | null | undefined
): { tier: BillingTier; expiresAt: string | null; lookupKey: string | null; recognised: boolean } {
  const none = { tier: "free" as BillingTier, expiresAt: null, lookupKey: null, recognised: true };
  /* NOT recognised: there is nothing here to read at all. */
  if (!subscription || typeof subscription !== "object") return { ...none, recognised: false };

  const status = String((subscription as { status?: unknown }).status ?? "");
  /* A status we know and that is not entitled is a DEFINITIVE answer.
     A status we have never heard of is not — Stripe adding one would
     otherwise cancel everybody holding it. */
  if (!ENTITLED_STATUSES.includes(status)) {
    return { ...none, recognised: ALL_KNOWN_STATUSES.includes(status) };
  }

  const items = ((subscription as { items?: { data?: unknown[] } }).items?.data ?? []) as Array<Record<string, unknown>>;

  /* HIGHEST WINS, the same rule the store side uses. A subscription
     with two items is not something we create, but a Portal plan change
     can leave one mid-flight, and answering with whichever item sorted
     first would be a coin toss over somebody's plan. */
  let best: { rank: number; key: string } | null = null;
  for (const item of items) {
    const price = (item?.price ?? {}) as { lookup_key?: unknown };
    const key = typeof price.lookup_key === "string" ? price.lookup_key : "";
    const plan = STRIPE_LOOKUP_KEYS[key];
    if (!plan) continue;
    const rank = TIER_RANK.indexOf(plan.tier);
    if (!best || rank > best.rank) best = { rank, key };
  }
  /* Entitled, and nothing matched. See the note above: this is the
     downgrade-everybody case, so it is reported as unanswerable. */
  if (!best) return { ...none, recognised: false };

  /* `current_period_end` is a UNIX SECONDS integer, and it is the one
     field here that would silently be wrong rather than absent: read as
     milliseconds it lands in 1970 and every entitlement reads expired. */
  const end = (subscription as { current_period_end?: unknown }).current_period_end;
  const expiresAt = typeof end === "number" && Number.isFinite(end) ? new Date(end * 1000).toISOString() : null;

  return { tier: TIER_RANK[best.rank], expiresAt, lookupKey: best.key, recognised: true };
}

/* ---------- talking to Stripe ---------- */

/** Stripe takes form-encoded bodies, including for nested fields (`a[b]=c`). */
export function formEncode(params: Record<string, string | number | undefined | null>): string {
  const out = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v === undefined || v === null) continue;
    out.set(k, String(v));
  }
  return out.toString();
}

/**
 * One request to Stripe.
 *
 * THREE OUTCOMES, KEPT DISTINCT — the `fetchNote` rule, which by now is
 * the house style: `{ok, data}`, `{ok:false, missing:true}` for a
 * definitive 404, and `{ok:false}` for everything else. A caller that
 * cannot tell "Stripe says there is no such subscription" from "we
 * could not reach Stripe" would strip a paying student's tier because a
 * request timed out.
 *
 * `idempotencyKey` is passed on WRITES so a retried checkout creates one
 * session rather than two. Stripe's own mechanism; free to use.
 */
export async function stripeRequest(
  path: string,
  {
    secretKey,
    method = "GET",
    body,
    idempotencyKey,
    fetchImpl = fetch,
  }: {
    secretKey: string;
    method?: "GET" | "POST";
    body?: Record<string, string | number | undefined | null>;
    idempotencyKey?: string;
    fetchImpl?: typeof fetch;
  }
): Promise<{ ok: true; data: Record<string, unknown> } | { ok: false; missing?: true; status?: number; error: unknown }> {
  try {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${secretKey}`,
      "Stripe-Version": STRIPE_API_VERSION,
    };
    if (method === "POST") headers["Content-Type"] = "application/x-www-form-urlencoded";
    if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;

    const res = await fetchImpl(`${STRIPE_API}${path}`, {
      method,
      headers,
      body: method === "POST" ? formEncode(body || {}) : undefined,
    });
    if (res.status === 404) return { ok: false, missing: true, status: 404, error: new Error("Stripe: not found") };
    const data = await res.json().catch(() => ({}));
    if (!res.ok) return { ok: false, status: res.status, error: new Error(`Stripe returned ${res.status}`) };
    return { ok: true, data: data as Record<string, unknown> };
  } catch (error) {
    return { ok: false, error };
  }
}

/* ---------- the webhook signature ---------- */

const enc = new TextEncoder();
const toHex = (buf: ArrayBuffer) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");

/** Constant-time compare. Same reasoning as billing-webhook's: a `===` on a secret leaks how much of it was guessed. */
export function timingSafeEqual(a: string, b: string): boolean {
  const x = enc.encode(a);
  const y = enc.encode(b);
  let diff = x.length ^ y.length;
  const n = Math.max(x.length, y.length);
  for (let i = 0; i < n; i++) diff |= (x[i] ?? 0) ^ (y[i] ?? 0);
  return diff === 0;
}

/**
 * Parse `t=<ts>,v1=<hex>[,v1=<hex>]` — Stripe's `Stripe-Signature`.
 *
 * MULTIPLE `v1` VALUES ARE REAL and this is the detail a naive parser
 * gets wrong: during a signing-secret rotation Stripe sends one `v1`
 * per active secret, so a parser that keeps the last one it saw rejects
 * half the deliveries for the length of the rotation. They are all
 * collected and any match is accepted.
 */
export function parseStripeSignature(header: string | null): { t: string; v1: string[] } | null {
  if (!header) return null;
  let t = "";
  const v1: string[] = [];
  for (const part of header.split(",")) {
    const [k, ...rest] = part.trim().split("=");
    const value = rest.join("=").trim();
    if (k.trim() === "t") t = value;
    if (k.trim() === "v1" && value) v1.push(value);
  }
  if (!t || v1.length === 0) return null;
  return { t, v1 };
}

/** HMAC-SHA256 of `${t}.${rawBody}`, hex. THE RAW BODY — never a re-serialised one. */
export async function signStripePayload(secret: string, t: string, rawBody: string): Promise<string> {
  const key = await crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return toHex(await crypto.subtle.sign("HMAC", key, enc.encode(`${t}.${rawBody}`)));
}

/** How stale a delivery may be. A signature proves the body was signed, not that it was signed recently. */
export const MAX_SIGNATURE_AGE_MS = 5 * 60 * 1000;

/** Stripe's timestamp is UNIX SECONDS. Read as milliseconds every delivery looks 56,000 years old and is refused. */
export function stripeTimestampFresh(t: string, now = Date.now(), maxAgeMs = MAX_SIGNATURE_AGE_MS): boolean {
  const n = Number(t);
  if (!Number.isFinite(n) || n <= 0) return false;
  return Math.abs(now - n * 1000) <= maxAgeMs;
}
