/* ==================================================================
   measure-two-arm.mjs — does the STRUCTURE separate description from
   ghostwriting, and where does the note cap go?

   The first measurement disproved §3's premise. It assumed "locating
   a problem requires quoting their text"; the model located problems
   without quoting anything, so description and replacement wording
   were both novel prose and no threshold over novelty could separate
   them. It also had one arm: it looked for two populations inside a
   single sample and would have found a gap only by luck.

   THIS HAS TWO ARMS AND THE NEGATIVE POPULATION IS GENERATED BY
   CONSTRUCTION. Same essays, same model, same schema; one prompt is
   the one we would ship and the other is told to supply replacement
   wording. Any candidate rule is then scored on SEPARATION between
   arms rather than on structure within one — and the experiment can
   fail, because the ghostwriting exists whether or not the model
   volunteers it.

   IT PICKS NOTHING. The two parameters — how long a locator quote
   must be, how long a note may be — are printed as an OPERATING
   CHARACTERISTIC: the refusal rate in each arm at every candidate
   value. A person reads where the constrained arm is still near zero
   and the adversarial arm is near one hundred. That is what "size the
   cap from the constrained arm's residual" means done properly, and
   it is the alternative to the number nobody sized that the last run
   disproved.

   ------------------------------------------------------------------
   USAGE

     set OPENAI_API_KEY=sk-...
     node scripts\measure-two-arm.mjs --essay e.txt --rubric r.txt

   Options:
     --runs <n>      default 2, per arm
     --model <id>    default is the shipped SUMMARY_MODEL
     --json <file>   raw measurements, redacted unless --show-text
     --show-text     print quotes and notes. OFF BY DEFAULT: the quote
                     field is the student's own words by construction,
                     so this script leaks essay text unless told not
                     to. The ASAP licence forbids that, and the
                     default is the safe one because the corpus this
                     was built for is the restricted one.
     --dry-run       resolve everything, call nothing, spend nothing

   ------------------------------------------------------------------
   THE QUALITY CONTROL IS ON THE SAME PAGE AS THE REFUSALS

   A cap that refuses all the ghostwriting by making the feedback
   useless is not a fix — it is the ai-notes depth regression, which
   was measured at +189% words per key point by REMOVING a limit. So
   points per essay, words per note and how many distinct deficiencies
   the model actually used are printed beside the refusal counts,
   both arms. A rule that improves separation while collapsing those
   is buying the number with the product.
   ================================================================== */

import fs from "node:fs";
import path from "node:path";
import { ROOT, callVision } from "./lib/photo-calls.mjs";
import { productionModel } from "./lib/production-model.mjs";
import { ARMS, userMessage } from "./lib/essay-arms.mjs";
import { DEFICIENCIES, measurePoint, refusePoint, quoteVariety, essayFeedbackSchema } from "../src/essayPoints.js";

const argv = process.argv.slice(2);
const opt = (n, d = null) => {
  const i = argv.indexOf(n);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : d;
};
const has = (n) => argv.includes(n);

const essayFile = opt("--essay");
const rubricFile = opt("--rubric");
const jsonOut = opt("--json");
const runsPerArm = Math.max(1, Number(opt("--runs", "2")));
const dryRun = has("--dry-run");
const showText = has("--show-text");

if (!essayFile || !rubricFile) {
  console.error("usage: OPENAI_API_KEY=sk-... node scripts/measure-two-arm.mjs --essay e.txt --rubric r.txt");
  process.exit(1);
}
for (const f of [essayFile, rubricFile]) {
  if (!fs.existsSync(f)) {
    console.error(`no such file: ${f}`);
    process.exit(1);
  }
}
if (!dryRun && !process.env.OPENAI_API_KEY) {
  console.error("OPENAI_API_KEY is not set. Use --dry-run to check the inputs without calling anything.");
  process.exit(1);
}

const essay = fs.readFileSync(essayFile, "utf8");
const criteria = fs.readFileSync(rubricFile, "utf8");

/* THE MODEL THE FEATURE WILL USE, asked of the same function the
   ai-text adapter asks — not read out of a constant by name, and with
   no fallback to a hardcoded id. See scripts/lib/production-model.mjs
   for what the previous line did on the day a constant moves.

   `hasImages: false` is explicit because it is the assumption worth
   being deliberate about: essay feedback is text-only and paste-only,
   so this is the call site that changes if that ever stops being
   true. */
const model = opt("--model") || (await productionModel({ hasImages: false }));

console.log("=".repeat(72));
console.log("TWO-ARM — does the structure separate description from ghostwriting?");
console.log("=".repeat(72));
console.log(`model        ${model}`);
console.log(`arms         ${Object.values(ARMS).map((a) => `${a.id} (${a.what})`).join("\n             ")}`);
console.log(`runs         ${runsPerArm} per arm  (${runsPerArm * 2} provider calls)`);
console.log(`deficiencies ${DEFICIENCIES.length} in the closed set`);
console.log(`text         ${showText ? "SHOWN (--show-text)" : "withheld — the quote field is the student's own words"}`);

if (dryRun) {
  console.log("\n--dry-run: nothing was called and nothing was spent.");
  process.exit(0);
}

/* ---------- run both arms ---------- */

const measured = { constrained: [], adversarial: [] };
const perRun = { constrained: [], adversarial: [] };
const malformed = { constrained: 0, adversarial: 0 };

for (const arm of Object.values(ARMS)) {
  for (let run = 1; run <= runsPerArm; run++) {
    process.stderr.write(`${arm.id} ${run}/${runsPerArm}…\n`);
    const { json, error } = await callVision({
      apiKey: process.env.OPENAI_API_KEY,
      model,
      messages: [
        { role: "system", content: arm.system },
        { role: "user", content: userMessage({ essay, criteria }) },
      ],
      maxTokens: 2000,
      /* THE STRICT SCHEMA, for both arms. `deficiency-unknown` was 84 of
         318 constrained refusals on 24 September — a quarter of the
         operating characteristic measuring the model's paraphrasing
         rather than the no-writing constraint. Under the schema it is
         zero by construction, so the table measures the thing it is for.
         THIS MOVES THE TABLE: runs before and after are not comparable. */
      jsonSchema: essayFeedbackSchema(),
    });
    if (error) {
      console.error(`  ${arm.id} run ${run} failed: ${error}`);
      continue;
    }
    let points;
    try {
      /* The schema nests the points under \`reading\` since the per-genre
         branches (essaySchema.js). */
      points = JSON.parse(json.choices[0].message.content).reading?.points;
      if (!Array.isArray(points)) throw new Error("no points array");
    } catch (e) {
      malformed[arm.id]++;
      console.error(`  ${arm.id} run ${run}: output did not parse as the schema`);
      continue;
    }
    const ms = points.map((point) => ({ ...measurePoint({ point, essay, criteria }), arm: arm.id, run }));
    measured[arm.id].push(...ms);
    perRun[arm.id].push(ms);
  }
}

const total = measured.constrained.length + measured.adversarial.length;
if (total === 0) {
  console.error("\nno points were measured — both arms failed.");
  process.exit(1);
}

/* ---------- per-field metrics ---------- */

const pct = (xs, p) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length ? s[Math.min(s.length - 1, Math.floor((p / 100) * s.length))] : null;
};
const share = (xs, f) => (xs.length ? ((xs.filter(f).length / xs.length) * 100).toFixed(0) : "—");

console.log(`\n${"=".repeat(72)}`);
console.log("PER-FIELD METRICS");
console.log("=".repeat(72));
console.log("\n  arm            points  quote OK%  quote p50w  note p50w  note p90w  offered%");
for (const id of ["constrained", "adversarial"]) {
  const m = measured[id];
  console.log(
    `  ${id.padEnd(14)} ${String(m.length).padEnd(7)} ${share(m, (x) => x.quoteVerbatim).padEnd(10)} ` +
      `${String(pct(m.map((x) => x.quoteWords), 50)).padEnd(11)} ` +
      `${String(pct(m.map((x) => x.noteWords), 50)).padEnd(10)} ` +
      `${String(pct(m.map((x) => x.noteWords), 90)).padEnd(10)} ` +
      `${share(m, (x) => x.offeredSpans.length > 0)}`
  );
}

/* THE RESIDUAL. `note` is the only channel ghostwriting can use once
   the quote must be verbatim and the deficiency is an enum, so its
   length distribution in the CONSTRAINED arm is what a cap is read
   off — and the adversarial arm's is what the cap has to exclude. */
console.log("\nNOTE LENGTH — the residual, and the only free-text channel:\n");
console.log("  arm            min   p50   p75   p90   p99   max");
for (const id of ["constrained", "adversarial"]) {
  const xs = measured[id].map((x) => x.noteWords);
  if (!xs.length) continue;
  console.log(
    `  ${id.padEnd(14)} ${String(pct(xs, 0)).padEnd(5)} ${String(pct(xs, 50)).padEnd(5)} ${String(pct(xs, 75)).padEnd(5)} ` +
      `${String(pct(xs, 90)).padEnd(5)} ${String(pct(xs, 99)).padEnd(5)} ${Math.max(...xs)}`
  );
}

/* ---------- the operating characteristic ---------- */

console.log(`\n${"=".repeat(72)}`);
console.log("OPERATING CHARACTERISTIC — refusal rate per arm, at every candidate");
console.log("=".repeat(72));
console.log(`
  Read DOWN for the note cap and ACROSS for the quote floor. A usable
  pair keeps the constrained column near 0 and the adversarial column
  near 100. If no cell does both, the structure does not separate them
  either and that is the finding.
`);
const QUOTE_FLOORS = [3, 4, 5, 6, 8];
const NOTE_CAPS = [12, 16, 20, 25, 30, 40, 60];
console.log("  note cap |" + QUOTE_FLOORS.map((q) => `  q>=${q}w        `).join(""));
console.log("           |" + QUOTE_FLOORS.map(() => "  con%  adv%    ").join(""));
for (const cap of NOTE_CAPS) {
  let row = `  ${String(cap).padStart(8)} |`;
  for (const floor of QUOTE_FLOORS) {
    const rate = (id) => {
      const m = measured[id];
      if (!m.length) return "—";
      const refused = m.filter((x) => !refusePoint(x, { minQuoteWords: floor, maxNoteWords: cap }).ok).length;
      return ((refused / m.length) * 100).toFixed(0);
    };
    row += `  ${rate("constrained").padStart(4)}  ${rate("adversarial").padStart(4)}    `;
  }
  console.log(row);
}

/* Which rule did the refusing, so a cell that separates can be read
   for WHY — a separation driven entirely by `wording-offered` is a
   different finding from one driven by the cap. */
console.log("\nWHY POINTS WERE REFUSED (at q>=4w, cap 25w):\n");
const codes = {};
for (const id of ["constrained", "adversarial"]) {
  codes[id] = {};
  for (const m of measured[id]) {
    for (const r of refusePoint(m, { minQuoteWords: 4, maxNoteWords: 25 }).reasons) {
      codes[id][r] = (codes[id][r] || 0) + 1;
    }
  }
}
const allCodes = [...new Set([...Object.keys(codes.constrained), ...Object.keys(codes.adversarial)])];
console.log("  reason                 constrained  adversarial");
for (const c of allCodes.sort()) {
  console.log(`  ${c.padEnd(22)} ${String(codes.constrained[c] || 0).padEnd(12)} ${codes.adversarial[c] || 0}`);
}

/* WHICH RULE IS ACTUALLY DOING THE WORK, said out loud rather than
   left in a table for somebody to notice. A pair of columns reading
   0 / 100 at EVERY cap means the cap is contributing nothing and one
   other rule is carrying the separation — so adopting that cap would
   be adopting a number that does not bite, and the real defence would
   be a single detector that a model can evade by dropping its quote
   marks. The first measurement failed for the mirror of this reason:
   a number that looked like it was measuring something. */
{
  const advTotal = measured.adversarial.length;
  const byRule = Object.entries(codes.adversarial).sort((a, b) => b[1] - a[1]);
  if (advTotal > 0 && byRule.length > 0) {
    const [topRule, topCount] = byRule[0];
    const capRefusals = measured.adversarial.filter((m) => m.noteWords > 25).length;
    console.log("");
    if (topCount >= advTotal && byRule.length === 1) {
      console.log(`  ALL adversarial refusals come from "${topRule}" alone.`);
      if (topRule === "wording-offered" && capRefusals === 0) {
        console.log(`  THE NOTE CAP IS CONTRIBUTING NOTHING HERE. Every ghostwritten note was`);
        console.log(`  caught because it QUOTED the wording it offered; a model that supplies`);
        console.log(`  replacement prose without quote marks would pass this rule entirely, and`);
        console.log(`  the cap is what would have to catch it. Do not read the 0/100 columns as`);
        console.log(`  evidence for a cap — they are evidence for one detector.`);
      }
    } else {
      console.log(`  Refusals are spread across ${byRule.length} rules; the cap is load-bearing.`);
    }
  }
}

/* ---------- the quality control ---------- */

console.log(`\n${"=".repeat(72)}`);
console.log("QUALITY CONTROL — a rule that buys separation by making the feedback useless");
console.log("=".repeat(72));
console.log("\n  arm            pts/run  distinct deficiencies  quote variety  quote spread  malformed");
for (const id of ["constrained", "adversarial"]) {
  const runs = perRun[id];
  const ptsPerRun = runs.length ? (runs.reduce((a, r) => a + r.length, 0) / runs.length).toFixed(1) : "—";
  const defs = new Set(measured[id].filter((m) => m.deficiencyKnown).map((m) => m.deficiency)).size;
  const v = quoteVariety(measured[id]);
  console.log(
    `  ${id.padEnd(14)} ${String(ptsPerRun).padEnd(8)} ${String(`${defs} of ${DEFICIENCIES.length}`).padEnd(22)} ` +
      `${String(v.ratio === null ? "—" : v.ratio.toFixed(2)).padEnd(14)} ` +
      `${String(v.spread === null ? "—" : v.spread.toFixed(2)).padEnd(13)} ${malformed[id]}`
  );
}
console.log(`
  QUOTE VARIETY is distinct quotes / points with a quote. A model
  quoting the same opening sentence every time passes "there is a
  verbatim quote" and locates nothing; a ratio near 1 with a wide
  SPREAD (0 = all in one place, 1 = across the whole essay) is what
  real locating looks like. Reported, never enforced — two problems
  in one sentence is legitimate.
`);

if (showText) {
  console.log(`${"=".repeat(72)}\nPOINTS IN FULL — read these for QUALITY; no number above does\n${"=".repeat(72)}`);
  for (const id of ["constrained", "adversarial"]) {
    console.log(`\n--- ${id} ---`);
    for (const m of measured[id].slice(0, 12)) {
      console.log(`  [${m.deficiency}] quote(${m.quoteWords}w): ${m.quoteNormalised.slice(0, 70)}`);
    }
  }
}

if (jsonOut) {
  const forFile = showText
    ? measured
    : Object.fromEntries(
        Object.entries(measured).map(([k, v]) => [k, v.map(({ quoteNormalised, ...rest }) => rest)])
      );
  fs.writeFileSync(jsonOut, JSON.stringify({ model, redacted: !showText, malformed, measured: forFile }, null, 2));
  console.log(`  raw measurements written to ${jsonOut}\n`);
}
