/* ==================================================================
   aiNotesLogic.js — AI lecture notes, framework-free logic

   Everything here is a plain function operating on plain data, no
   React and no browser-only globals baked in (the few that touch
   browser APIs take them as an injected parameter). That's what lets
   scripts/test-ai-notes.mjs exercise all of it directly from Node.
   ================================================================== */

/* ---------- consent gate ---------- */

// Bump this whenever CONSENT_TEXT's wording changes materially — every
// user who accepted an older version gets re-prompted on next load.
export const AI_CONSENT_VERSION = 1;

export const CONSENT_TEXT = {
  title: "Before you record a lecture",
  bullets: [
    "These notes are generated by AI to assist study. They are not a substitute for the student's own notes and may contain mistakes.",
    "You are responsible for having permission to record. Many universities require the lecturer's consent, and recording people without permission may be unlawful in some Australian states.",
    "Audio is sent to a third-party service for transcription and is not retained afterwards.",
  ],
  acceptLabel: "I understand and agree",
};

/** True when the signed-in user hasn't accepted the current consent wording. */
export function needsConsent(meta, version = AI_CONSENT_VERSION) {
  const consent = meta && meta.aiConsent;
  if (!consent) return true;
  return (consent.version || 0) < version;
}

/** Patch to merge into `data.meta` when the user accepts. */
export function buildConsentPatch(version = AI_CONSENT_VERSION, nowISO = () => new Date().toISOString()) {
  return { aiConsent: { version, acceptedAt: nowISO() } };
}

/* ---------- the idempotency key ----------

   Must be a real UUID. `ai_notes_requests.idempotency_key` is typed
   `uuid`, so anything else is rejected by Postgres with 22P02 (invalid
   input syntax) and the recording never gets processed.

   This is deliberately NOT the planner's `uid()` helper, which mints
   short ids like "msn0duf5-hk684" for notes and pages. Those are stored
   in the user's own JSON blob where the format doesn't matter; this one
   crosses into a typed database column where it does. Using uid() here
   is exactly the bug this replaces.
   ------------------------------------------ */

const UUID_HEX = "0123456789abcdef";

/**
 * A v4 UUID.
 *
 * `crypto.randomUUID` is the right answer where it exists, but it is
 * absent in non-secure contexts and on older WebKit — which is precisely
 * where this app runs once it's wrapped in an iOS or Android WebView, and
 * the hardest place to notice a bad value. So the fallbacks matter, and
 * every one of them must produce a genuinely well-formed UUID: a
 * fallback that returns some other random string would reintroduce the
 * 22P02 failure on exactly the platforms that are hardest to debug.
 *
 * `cryptoObj` is injected so the fallback paths are testable.
 */
export function newIdempotencyKey(cryptoObj = typeof globalThis !== "undefined" ? globalThis.crypto : undefined) {
  if (cryptoObj && typeof cryptoObj.randomUUID === "function") {
    return cryptoObj.randomUUID();
  }

  const bytes = new Uint8Array(16);
  if (cryptoObj && typeof cryptoObj.getRandomValues === "function") {
    // Available in non-secure contexts and much older browsers than
    // randomUUID, so this covers most of the gap.
    cryptoObj.getRandomValues(bytes);
  } else {
    // Last resort. Weaker randomness, but an idempotency key only has to
    // be unique per recording, not unguessable.
    for (let i = 0; i < 16; i++) bytes[i] = Math.floor(Math.random() * 256);
  }

  bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
  bytes[8] = (bytes[8] & 0x3f) | 0x80; // variant 1 (RFC 4122)

  let out = "";
  for (let i = 0; i < 16; i++) {
    if (i === 4 || i === 6 || i === 8 || i === 10) out += "-";
    out += UUID_HEX[bytes[i] >> 4] + UUID_HEX[bytes[i] & 0x0f];
  }
  return out;
}

/* ---------- recording format ---------- */

// Speech doesn't need music-quality bitrate. 32kbps keeps a 3-hour
// recording to ~43.2MB — well under Supabase Storage's 50MB/file
// free-tier ceiling. If this changes, the Edge Function's
// MAX_BODY_BYTES (supabase/functions/ai-notes/config.ts) must change
// with it, since that constant assumes this bitrate.
export const RECORDER_AUDIO_BITS_PER_SECOND = 32000;

// Display-only hint for the "X of Y minutes used" badge and the
// near-cap warning banner. The real limit is enforced server-side
// (supabase/functions/ai-notes/config.ts MONTHLY_MINUTES_LIMIT) — if
// this drifts out of sync with that constant it's a cosmetic issue,
// not a security one, since the server never trusts the client's copy.
export const MONTHLY_MINUTES_LIMIT_HINT = 300;

const CANDIDATE_MIME_TYPES = [
  { mimeType: "audio/webm;codecs=opus", extension: "webm" },
  { mimeType: "audio/webm", extension: "webm" },
  { mimeType: "audio/mp4", extension: "m4a" },
  { mimeType: "audio/aac", extension: "aac" },
];

/**
 * Picks the first mime type the platform's MediaRecorder actually
 * supports. `isSupportedFn` is injected (defaults to the real
 * `MediaRecorder.isTypeSupported`) so this is testable in Node,
 * where no MediaRecorder exists at all.
 */
export function pickSupportedMimeType(isSupportedFn) {
  const isSupported =
    isSupportedFn || (typeof MediaRecorder !== "undefined" && MediaRecorder.isTypeSupported.bind(MediaRecorder));
  if (!isSupported) return null;
  for (const candidate of CANDIDATE_MIME_TYPES) {
    if (isSupported(candidate.mimeType)) return candidate;
  }
  return null;
}

/* ---------- error messages ---------- */

/** Maps a getUserMedia/MediaRecorder DOMException to a friendly sentence. */
export function describeRecorderError(err) {
  const name = (err && err.name) || "";
  switch (name) {
    case "NotAllowedError":
    case "PermissionDeniedError":
      return "Microphone access was denied. Please allow microphone access in your browser or device settings to record a lecture.";
    case "NotFoundError":
    case "DevicesNotFoundError":
      return "No microphone was found on this device.";
    case "NotReadableError":
    case "TrackStartError":
      return "Your microphone is being used by another app. Close other apps that might be using it and try again.";
    default:
      return "Something went wrong accessing the microphone. Please try again.";
  }
}

// Codes in this set mean retrying with the same recording would fail
// identically (the provider rejected it outright, not a transient
// hiccup) — the UI uses this to withhold the "Try again" option, since
// offering it would just strand the user in a loop.
export const PERMANENT_FAILURE_CODES = new Set([
  "recording_too_long",
  "transcription_too_long",
  // The key is minted once and reused across retries, so a malformed one
  // fails identically every time — the fix is reloading, not retrying.
  "bad_idempotency_key",
]);

const ERROR_MESSAGES = {
  no_access: "AI notes isn't enabled for your account yet.",
  usage_exceeded: "You've used all your AI minutes for this month.",
  already_processing: "This recording is already being processed — try again shortly.",
  recording_too_long: "Recordings are limited to about 3 hours.",
  recording_missing: "We couldn't find that recording — please record it again.",
  transcription_failed: "We couldn't transcribe that recording. Please try again.",
  transcription_too_long: "This recording is too long to process — try recording in shorter segments.",
  unauthenticated: "Please sign in again to use AI notes.",
  // Only reachable from a stale cached copy of the app: current builds
  // mint a UUID. Telling the user to reload is what actually fixes it.
  bad_idempotency_key: "Please reload the app and try recording again.",
};

/** Maps the ai-notes Edge Function's JSON error body to a friendly sentence. */
export function parseAiNotesError(json, status) {
  const code = json && json.code;
  if (code && ERROR_MESSAGES[code]) return ERROR_MESSAGES[code];
  if (json && json.error) return json.error;
  return `Something went wrong (${status || "network error"}). Please try again.`;
}

/* ---------- translation languages ---------- */

export const TRANSLATION_LANGUAGES = [
  { code: "zh", label: "Simplified Chinese" },
  { code: "hi", label: "Hindi" },
  { code: "ne", label: "Nepali" },
  { code: "vi", label: "Vietnamese" },
  { code: "bn", label: "Bengali" },
  { code: "id", label: "Indonesian" },
  { code: "ko", label: "Korean" },
  { code: "th", label: "Thai" },
  { code: "es", label: "Spanish" },
  { code: "ar", label: "Arabic" },
];

/* ---------- mapping AI output onto the app's existing data shapes ----------

   AI notes are stored as a normal `pages` item (the same collection as
   handwritten notebook pages, so folders/future search already cover
   it) plus one `notes` item per term/definition pair (the collection
   the Study cards game already reads). Both collections live inside
   the single `planner_data` JSON blob that syncs in full on every
   change (see 4-BACKEND-GUIDE.md) — AI notes are meaningfully bigger
   than manual notes, so if sync ever gets noticeably slower, splitting
   AI notes into their own table/row is the documented escape hatch,
   not a problem to pre-solve here.
------------------------------------------------------------------- */

/* How much of a failed transcript is kept in the synced planner.

   Transcripts are enormous relative to everything else in the blob: a
   two-hour lecture is roughly 15,000 spoken words, which measures ~88KB
   — forty times a typical notebook page. Storing one whole was a live
   bug, and it fired at the worst moment, when summarising had already
   failed and the user was least able to afford a second problem.

   2000 characters is about 300 words: enough to recognise which lecture
   this is and to see the transcription worked, at ~2KB instead of 88.
   The rest isn't discarded — the full text is still in memory on the
   review screen and is offered as a download (see aiNotes.jsx). What is
   NOT done is silently putting 88KB into a blob that syncs in full on
   every keystroke. */
export const TRANSCRIPT_EXCERPT_CHARS = 2000;

/**
 * The opening of a transcript, cut at a word boundary.
 *
 * Returns what was kept along with the original length, so the caller
 * can tell the user how much more there is rather than leaving them to
 * wonder whether the recording cut out.
 */
export function truncateTranscript(transcript, limit = TRANSCRIPT_EXCERPT_CHARS) {
  const full = typeof transcript === "string" ? transcript : "";
  if (full.length <= limit) {
    return { text: full, truncated: false, fullLength: full.length };
  }
  const slice = full.slice(0, limit);
  const lastSpace = slice.lastIndexOf(" ");
  // Only honour the word boundary if it isn't throwing away a big chunk
  // of the excerpt -- a transcript with no spaces at all shouldn't
  // collapse to nothing.
  const text = lastSpace > limit * 0.8 ? slice.slice(0, lastSpace) : slice;
  return { text, truncated: true, fullLength: full.length };
}

function formatBody({ overview, keyPoints, assessable, openQuestions }) {
  const parts = [overview || ""];
  if (keyPoints && keyPoints.length) {
    parts.push("", "Key points:", ...keyPoints.map((p) => `• ${p}`));
  }
  if (assessable && assessable.length) {
    parts.push("", "Might be assessed:", ...assessable.map((p) => `• ${p}`));
  }
  if (openQuestions && openQuestions.length) {
    parts.push("", "Open questions:", ...openQuestions.map((p) => `• ${p}`));
  }
  return parts.join("\n");
}

/**
 * Pure mapper from the Edge Function's structured result to the two
 * kinds of items the app already knows how to render, sync and study.
 */
export function mapAiResultToItems({ result, course, week, language, uid, nowISO }) {
  const title = `${course || "Lecture"} — Week ${week || "?"} notes`;

  if (result.summaryFailed) {
    const excerpt = truncateTranscript(result.transcript);
    const header = "Transcript (AI summary failed — you can re-run summarizing later or edit this by hand):";
    // No aiMeta on this page, deliberately. aiMeta routes a page to the
    // AI viewer, which is read-only; this one has to open in the normal
    // editor so "edit this by hand" is actually possible.
    return {
      pageItem: {
        id: uid(),
        title,
        body: excerpt.truncated
          ? `${header}\n\n${excerpt.text}\n\n[Only the first ${excerpt.text.length.toLocaleString()} characters are saved here, of ${excerpt.fullLength.toLocaleString()}. Download the full transcript from the recording screen before you leave it — it isn't kept afterwards.]`
          : `${header}\n\n${excerpt.text}`,
        html: "",
        strokes: [],
        style: "lined",
        kind: "text",
        font: "sans",
        folderId: null,
      },
      noteItems: [],
    };
  }

  const translations = { en: result.original };
  if (result.translated && language) translations[language] = result.translated;

  return {
    pageItem: {
      id: uid(),
      title,
      body: formatBody(result.original),
      html: "",
      strokes: [],
      style: "lined",
      kind: "text",
      font: "sans",
      folderId: null,
      aiMeta: {
        course,
        week,
        generatedAt: nowISO(),
        activeLanguage: "en",
        translations,
      },
    },
    noteItems: (result.original.terms || []).map((t) => ({
      id: uid(),
      course,
      week,
      term: t.term,
      content: t.content,
    })),
  };
}

/* ---------- recording state machine ----------

   idle -> requesting -> recording <-> paused -> stopped -> uploading -> review -> saving -> done
                  \-> error (mic denied, blob never existed)
                                            uploading/saving -> error (blob PRESERVED — retry doesn't lose the recording)

   `blob` is only ever cleared by "discard" or "saved" — every error/
   retry transition leaves it untouched, which is what makes "a failed
   transcription doesn't lose the user's recording" a property of the
   reducer rather than a manual QA claim.
------------------------------------------------------------------- */

export const INITIAL_RECORDER_STATE = {
  status: "idle",
  blob: null,
  mimeType: null,
  idempotencyKey: null,
  estimatedDurationSeconds: 0,
  path: null,
  result: null,
  errorCode: null,
  errorMessage: null,
};

export function recorderReducer(state, action) {
  switch (action.type) {
    case "request":
      return { ...state, status: "requesting", errorMessage: null, errorCode: null };

    case "requestDenied":
      return {
        ...INITIAL_RECORDER_STATE,
        status: "error",
        errorMessage: action.message,
      };

    case "started":
      return { ...state, status: "recording" };

    case "pause":
      return state.status === "recording" ? { ...state, status: "paused" } : state;

    case "resume":
      return state.status === "paused" ? { ...state, status: "recording" } : state;

    case "stop":
      // idempotencyKey is minted once here and stays stable across every
      // retry of *this* recording, so a client retry after a timeout
      // reuses the same key instead of risking a double-billed duplicate.
      return {
        ...state,
        status: "stopped",
        blob: action.blob,
        mimeType: action.mimeType,
        idempotencyKey: action.idempotencyKey,
        estimatedDurationSeconds: action.estimatedDurationSeconds,
      };

    case "discard":
      return { ...INITIAL_RECORDER_STATE };

    case "upload":
      return state.blob ? { ...state, status: "uploading", errorMessage: null, errorCode: null } : state;

    case "uploaded":
      return { ...state, status: "uploading", path: action.path };

    case "uploadFailed":
      return { ...state, status: "error", errorCode: action.code, errorMessage: action.message };

    case "processed":
      return { ...state, status: "review", result: action.result };

    case "retry":
      // Only meaningful from "error", and only if there's still a blob
      // to retry with — otherwise there's nothing to do but discard.
      return state.blob ? { ...state, status: "uploading", errorMessage: null, errorCode: null } : state;

    case "save":
      return { ...state, status: "saving" };

    case "saveFailed":
      return { ...state, status: "review", errorMessage: action.message };

    case "saved":
      return { ...INITIAL_RECORDER_STATE, status: "done" };

    case "reset":
      return { ...INITIAL_RECORDER_STATE };

    default:
      return state;
  }
}
