/* ==================================================================
   aiNotesLogic.js — AI lecture notes, framework-free logic

   Everything here is a plain function operating on plain data, no
   React and no browser-only globals baked in (the few that touch
   browser APIs take them as an injected parameter). That's what lets
   scripts/test-ai-notes.mjs exercise all of it directly from Node.
   ================================================================== */

import { RESULT_RETENTION_DAYS, FAILED_RESULT_RETENTION_DAYS } from "./aiNotesRetention.js";
import { PRIVACY_URL } from "./legalLinks.js";

/* ---------- consent gate ---------- */

// Bump this whenever CONSENT_TEXT's wording changes materially — every
// user who accepted an older version gets re-prompted on next load.
/* v5 covers TEXT THE STUDENT SUPPLIES, whatever its origin.

   The version history, because each bump had one reason:
     v1  audio isn't retained
     v2  + the server keeps a copy of the transcript and notes
     v3  + where that server is, why each period is what it is, and a
         link to the published policy
     v4  + AI features that work on text the student already wrote
     v5  + text the student supplies of ANY origin, not only their own
         writing -- and that we never store it

   WHY v4 WAS TOO NARROW, and why the fix is a category rather than
   another instance. v4 said "writing you have already done", which
   describes a note or an explanation and not a paragraph of a textbook
   pasted in to be summarised. But the narrowness was already there
   before readings existed: a lecture recording captures a lecturer's
   copyrighted delivery, so the app has ALWAYS worked on material the
   student did not write. Lecture audio was an example of the category,
   not a separate thing beside it.

   So v5 names the category -- text and audio the student supplies, of
   whatever origin, relayed to do the thing they asked and, for text,
   not stored at all -- rather than listing another feature. The next
   feature that takes supplied text needs no bump.

   V6 WIDENS THE CATEGORY THE SAME WAY: text, audio and IMAGES the
   student supplies. Photographed pages are images of text, and arguing
   a photo is "text you supply" is exactly the wordsmithing v5 exists
   to prevent. The bump test passes in both directions: a new kind of
   material leaves the country (a photo can capture more than the words
   -- margins, a hand, whatever is behind the book), and the same
   promise is made about it (relayed, never stored). Same move as v5,
   one category wider.

   BUMPED because what happens to the content changed in a way a student
   can meaningfully agree to: a new kind of material goes overseas, and
   a new promise is made about it (nothing is kept). That is the test --
   the storage move did NOT bump, because the row simply moved tables.

   Being slightly over-broad ahead of a feature is harmless. Being
   under-broad after it ships is the failure that matters, and it is the
   one that would have happened.

   The three artifacts still have three lifetimes and the wording still
   has to keep them apart, because "we keep your lecture" reads as the
   recording if written carelessly:

     the recording   -> deleted as soon as transcription succeeds
     the server copy -> 7 days, 30 if summarising failed
     the saved note  -> the user's, until they delete it

   Retention numbers are interpolated from aiNotesRetention.js rather
   than typed, so the promise cannot drift from what the server
   enforces. Every clause is checked against the code by a test. */
export const AI_CONSENT_VERSION = 6;

export const CONSENT_TEXT = {
  title: "Before you use the AI features",
  bullets: [
    "These notes and answers are generated by AI to assist study. They are not a substitute for the student's own work and may contain mistakes.",
    "If you record a lecture, you are responsible for having permission. Many universities require the lecturer's consent, and recording people without permission may be unlawful in some Australian states.",
    "Your recording is sent overseas to a transcription service, and the transcript is sent to a summarising service. Your recording is deleted as soon as it has been transcribed. It is never kept.",
    "Some AI features work on text or photos you supply — a note you wrote, your study cards, an explanation you type, a section of a reading you paste in, or photos of pages you're studying. When you use one, what you supplied is sent overseas to the same summarising service to do what you asked, and it is not stored: not in your planner and not on our server. Only the result is saved, and only if you save it.",
    "It is your responsibility to have the right to use whatever you supply. These features are for your own study — a summary is something to revise from alongside the material, not a replacement for it.",
    `A copy of the transcript and notes stays on our server in Sydney for ${RESULT_RETENTION_DAYS} days so you can get them back if something goes wrong — or ${FAILED_RESULT_RETENTION_DAYS} days if we couldn't finish, so nothing you paid for is lost. The notes you save into your planner are yours until you delete them.`,
  ],
  acceptLabel: "I understand and agree",
  privacyLabel: "Read the privacy policy",
  privacyUrl: PRIVACY_URL,
};

/** True when the signed-in user hasn't accepted the current consent wording. */
export function needsConsent(meta, version = AI_CONSENT_VERSION) {
  const consent = meta && meta.aiConsent;
  if (!consent) return true;
  return (consent.version || 0) < version;
}

/** Patch to merge into `data.meta` when the user accepts. */
export function buildConsentPatch(version = AI_CONSENT_VERSION, nowISO = () => new Date().toISOString()) {
  return { aiConsent: { version, acceptedAt: nowISO() } };
}

/* ---------- the idempotency key ----------

   Must be a real UUID. `ai_notes_requests.idempotency_key` is typed
   `uuid`, so anything else is rejected by Postgres with 22P02 (invalid
   input syntax) and the recording never gets processed.

   This is deliberately NOT the planner's `uid()` helper, which mints
   short ids like "msn0duf5-hk684" for notes and pages. Those are stored
   in the user's own JSON blob where the format doesn't matter; this one
   crosses into a typed database column where it does. Using uid() here
   is exactly the bug this replaces.
   ------------------------------------------ */

const UUID_HEX = "0123456789abcdef";

/**
 * A v4 UUID.
 *
 * `crypto.randomUUID` is the right answer where it exists, but it is
 * absent in non-secure contexts and on older WebKit — which is precisely
 * where this app runs once it's wrapped in an iOS or Android WebView, and
 * the hardest place to notice a bad value. So the fallbacks matter, and
 * every one of them must produce a genuinely well-formed UUID: a
 * fallback that returns some other random string would reintroduce the
 * 22P02 failure on exactly the platforms that are hardest to debug.
 *
 * `cryptoObj` is injected so the fallback paths are testable.
 */
export function newIdempotencyKey(cryptoObj = typeof globalThis !== "undefined" ? globalThis.crypto : undefined) {
  if (cryptoObj && typeof cryptoObj.randomUUID === "function") {
    return cryptoObj.randomUUID();
  }

  const bytes = new Uint8Array(16);
  if (cryptoObj && typeof cryptoObj.getRandomValues === "function") {
    // Available in non-secure contexts and much older browsers than
    // randomUUID, so this covers most of the gap.
    cryptoObj.getRandomValues(bytes);
  } else {
    // Last resort. Weaker randomness, but an idempotency key only has to
    // be unique per recording, not unguessable.
    for (let i = 0; i < 16; i++) bytes[i] = Math.floor(Math.random() * 256);
  }

  bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
  bytes[8] = (bytes[8] & 0x3f) | 0x80; // variant 1 (RFC 4122)

  let out = "";
  for (let i = 0; i < 16; i++) {
    if (i === 4 || i === 6 || i === 8 || i === 10) out += "-";
    out += UUID_HEX[bytes[i] >> 4] + UUID_HEX[bytes[i] & 0x0f];
  }
  return out;
}

/* ---------- recording format ---------- */

// Speech doesn't need music-quality bitrate. 32kbps keeps a 3-hour
// recording to ~43.2MB — well under Supabase Storage's 50MB/file
// free-tier ceiling. If this changes, the Edge Function's
// MAX_BODY_BYTES (supabase/functions/ai-notes/config.ts) must change
// with it, since that constant assumes this bitrate.
export const RECORDER_AUDIO_BITS_PER_SECOND = 32000;

// THE MONTHLY LIMIT MOVED to src/aiTextLimits.js, which is now the
// client's copy of the whole currency rather than of the text half.
// Two mirrors of one number is one mirror too many, and this one spent
// several months with a comment where its assertion should have been.
// Import MONTHLY_CREDITS_LIMIT from there.

/* Mirrored from the Edge Function's MINIMUM_BILLED_CREDITS, for the same
   reason TRANSLATION_LANGUAGES is mirrored: the browser bundle can't
   import from supabase/functions/. A test asserts the two agree.

   Not cosmetic. It is what a student sees their allowance move by, so a
   drift here makes the number on screen disagree with the number being
   charged. */
export const MINIMUM_BILLED_CREDITS_HINT = 3;

/* What a re-summarise costs in credits, mirrored for the copy that has to state it
   before the student commits. A browser bundle cannot import from
   supabase/functions, so this is the allowed kind of restatement — and
   the EQUALITY is the guard: test-ai-notes.mjs asserts it against the
   server's derived constant, because a figure on screen that disagrees
   with the figure charged is the failure this pattern exists to stop. */
export const RESUMMARISE_BILLED_CREDITS_HINT = 2;

const CANDIDATE_MIME_TYPES = [
  { mimeType: "audio/webm;codecs=opus", extension: "webm" },
  { mimeType: "audio/webm", extension: "webm" },
  { mimeType: "audio/mp4", extension: "m4a" },
  { mimeType: "audio/aac", extension: "aac" },
];

/**
 * Picks the first mime type the platform's MediaRecorder actually
 * supports. `isSupportedFn` is injected (defaults to the real
 * `MediaRecorder.isTypeSupported`) so this is testable in Node,
 * where no MediaRecorder exists at all.
 */
export function pickSupportedMimeType(isSupportedFn) {
  const isSupported =
    isSupportedFn || (typeof MediaRecorder !== "undefined" && MediaRecorder.isTypeSupported.bind(MediaRecorder));
  if (!isSupported) return null;
  for (const candidate of CANDIDATE_MIME_TYPES) {
    if (isSupported(candidate.mimeType)) return candidate;
  }
  return null;
}

/* ---------- error messages ---------- */

/** Maps a getUserMedia/MediaRecorder DOMException to a friendly sentence. */
export function describeRecorderError(err) {
  const name = (err && err.name) || "";
  switch (name) {
    case "NotAllowedError":
    case "PermissionDeniedError":
      return "Microphone access was denied. Please allow microphone access in your browser or device settings to record a lecture.";
    case "NotFoundError":
    case "DevicesNotFoundError":
      return "No microphone was found on this device.";
    case "NotReadableError":
    case "TrackStartError":
      return "Your microphone is being used by another app. Close other apps that might be using it and try again.";
    default:
      return "Something went wrong accessing the microphone. Please try again.";
  }
}

/* ---------- absence has to be proven ----------

   THE RULE, and this is its second occurrence: NEVER TREAT A FAILED
   REQUEST AS EVIDENCE OF ABSENCE. A dropped connection, a 500, an
   expired token and a rate limit all look like "no data" to a caller
   that only checks whether it got something back -- and this code runs
   precisely when the network is misbehaving.

   The first occurrence is fetchNote in aiNotesStore.js, which returns
   three outcomes for exactly this reason. This is the same distinction
   in the one place where the thing at stake has ALREADY BEEN BILLED:
   the recovery card is the only handle a student has on a summary they
   paid for, and throwing the key away on a transient error makes it
   unreachable while the server still holds it for days.

   Only these two are definitive:

     recording_missing    the function looked in the bucket and there is
                          nothing there -- swept, or never uploaded
     bad_idempotency_key  the stored key is malformed, so every future
                          attempt fails identically; keeping it would
                          leave a card that can never succeed

   EVERYTHING ELSE IS "failed", including an error with no code at all
   (a fetch that rejects outright). Failing this way round is the cheap
   direction: keeping a key whose result is really gone costs a card the
   student can dismiss, while discarding a live one costs them a lecture. */
export const RECOVERY_MISSING_CODES = new Set(["recording_missing", "bad_idempotency_key"]);

/** "missing" (definitively not there) or "failed" (we do not know). */
export function recoveryFailureKind(err) {
  const code = err && err.code;
  return code && RECOVERY_MISSING_CODES.has(code) ? "missing" : "failed";
}

// Codes in this set mean retrying with the same recording would fail
// identically (the provider rejected it outright, not a transient
// hiccup) — the UI uses this to withhold the "Try again" option, since
// offering it would just strand the user in a loop.
export const PERMANENT_FAILURE_CODES = new Set([
  "recording_too_long",
  "transcription_too_long",
  // The key is minted once and reused across retries, so a malformed one
  // fails identically every time — the fix is reloading, not retrying.
  "bad_idempotency_key",
]);

const ERROR_MESSAGES = {
  no_access: "AI notes isn't enabled for your account yet.",
  usage_exceeded: "You've used all your AI minutes for this month.",
  already_processing: "This recording is already being processed — try again shortly.",
  recording_too_long: "Recordings are limited to about 3 hours.",
  recording_missing: "We couldn't find that recording — please record it again.",
  transcription_failed: "We couldn't transcribe that recording. Please try again.",
  transcription_too_long: "This recording is too long to process — try recording in shorter segments.",
  unauthenticated: "Please sign in again to use AI notes.",
  // Only reachable from a stale cached copy of the app: current builds
  // mint a UUID. Telling the user to reload is what actually fixes it.
  bad_idempotency_key: "Please reload the app and try recording again.",
};

/** Maps the ai-notes Edge Function's JSON error body to a friendly sentence. */
export function parseAiNotesError(json, status) {
  const code = json && json.code;
  if (code && ERROR_MESSAGES[code]) return ERROR_MESSAGES[code];
  if (json && json.error) return json.error;
  return `Something went wrong (${status || "network error"}). Please try again.`;
}

/* ---------- translation languages ---------- */

export const TRANSLATION_LANGUAGES = [
  { code: "zh", label: "Simplified Chinese" },
  { code: "hi", label: "Hindi" },
  { code: "ne", label: "Nepali" },
  { code: "vi", label: "Vietnamese" },
  { code: "bn", label: "Bengali" },
  { code: "id", label: "Indonesian" },
  { code: "ko", label: "Korean" },
  { code: "th", label: "Thai" },
  { code: "es", label: "Spanish" },
  { code: "ar", label: "Arabic" },
];

/* ---------- mapping AI output onto the app's existing data shapes ----------

   AI notes are stored as a normal `pages` item (the same collection as
   typed notebook pages, so folders/future search already cover
   it) plus one `notes` item per term/definition pair (the collection
   the Study cards game already reads). Both collections live inside
   the single `planner_data` JSON blob that syncs in full on every
   change (see 4-BACKEND-GUIDE.md) — AI notes are meaningfully bigger
   than manual notes, so if sync ever gets noticeably slower, splitting
   AI notes into their own table/row is the documented escape hatch,
   not a problem to pre-solve here.
------------------------------------------------------------------- */

/* How much of a failed transcript is kept in the synced planner.

   Transcripts are enormous relative to everything else in the blob: a
   two-hour lecture is roughly 15,000 spoken words, which measures ~88KB
   — forty times a typical notebook page. Storing one whole was a live
   bug, and it fired at the worst moment, when summarising had already
   failed and the user was least able to afford a second problem.

   2000 characters is about 300 words: enough to recognise which lecture
   this is and to see the transcription worked, at ~2KB instead of 88.
   The rest isn't discarded — the full text is still in memory on the
   review screen and is offered as a download (see aiNotes.jsx). What is
   NOT done is silently putting 88KB into a blob that syncs in full on
   every keystroke. */
export const TRANSCRIPT_EXCERPT_CHARS = 2000;

/**
 * The opening of a transcript, cut at a word boundary.
 *
 * Returns what was kept along with the original length, so the caller
 * can tell the user how much more there is rather than leaving them to
 * wonder whether the recording cut out.
 */
export function truncateTranscript(transcript, limit = TRANSCRIPT_EXCERPT_CHARS) {
  const full = typeof transcript === "string" ? transcript : "";
  if (full.length <= limit) {
    return { text: full, truncated: false, fullLength: full.length };
  }
  const slice = full.slice(0, limit);
  const lastSpace = slice.lastIndexOf(" ");
  // Only honour the word boundary if it isn't throwing away a big chunk
  // of the excerpt -- a transcript with no spaces at all shouldn't
  // collapse to nothing.
  const text = lastSpace > limit * 0.8 ? slice.slice(0, lastSpace) : slice;
  return { text, truncated: true, fullLength: full.length };
}

/* ---------- what a stored AI note is allowed to cost ----------

   SUMMARY_MAX_TOKENS bounds what the model returns. It does not bound
   what we write into the planner, and those are different numbers: the
   summary used to be stored twice (rendered into page.body AND verbatim
   in aiMeta.translations.en) and the terms twice as well (as `notes`
   items and inside aiMeta), so a note cost roughly double what the
   model produced.

   Measured: a realistic two-hour lecture was 12.9KB stored (18.1KB with
   a translation); at the 8000-token ceiling it was 77KB, which is 4.5MB
   for a semester of lectures -- past the localStorage ceiling on its
   own. De-duplication takes the realistic case to ~7KB; this cap bounds
   the pathological one.

   20KB is about four times a realistic de-duplicated note, so a long or
   unusually dense lecture with a translation still fits and nobody
   legitimate is rejected. It is a guard against one runaway note, NOT a
   budget mechanism -- it does not make sixty lectures fit in 1MB. Only
   moving AI notes out of the synced blob does that; see CLAUDE.md. */
export const MAX_AI_NOTE_BYTES = 20 * 1024;

const byteLength = (value) => {
  const json = JSON.stringify(value) || "";
  return typeof TextEncoder !== "undefined" ? new TextEncoder().encode(json).length : json.length;
};

/**
 * The summary as it should be STORED, which is not the summary as
 * returned.
 *
 * `terms` are dropped: every term becomes a study card in the `notes`
 * collection, which is the canonical copy and the one the Study tab
 * reads. Keeping a second copy inside aiMeta cost ~25% of the page and
 * nothing rendered it -- AiLectureNoteView shows overview, keyPoints,
 * assessable and openQuestions only.
 */
export function summaryForStorage(summary) {
  if (!summary || typeof summary !== "object") return summary;
  const { terms, ...rest } = summary;
  return rest;
}

/* Order in which content is given up when a note is over the cap.
   Least valuable first: open questions are the model's own uncertainty,
   assessable is a subset of the key points, and the overview is the
   last thing to go because it is the note. */
const TRIM_ORDER = ["openQuestions", "assessable", "keyPoints"];

/**
 * Bring a note under MAX_AI_NOTE_BYTES, giving up the least valuable
 * content first, and report what was given up.
 *
 * THE DROP ORDER MATTERS AND IS NOT "TRANSLATION FIRST". A student who
 * asked for a translation is very likely reading the translation --
 * it may be the entire reason they used the feature. Dropping it would
 * leave them with a copy in the language they are less comfortable in,
 * while never affecting a monolingual user at all. So the language the
 * user ASKED FOR is kept and the other one goes.
 *
 * Nothing dropped here is regenerable: the audio is deleted as soon as
 * transcription succeeds and there is no text-only re-summarise
 * endpoint (see CLAUDE.md). It is recoverable from the server row for
 * the retention window, and the UI offers a download. "Regenerable" is
 * the wrong word and must not appear in user-facing copy.
 */
export function capAiNote({ pageItem, requestedLanguage = "en", limit = MAX_AI_NOTE_BYTES } = {}) {
  if (!pageItem || byteLength(pageItem) <= limit) {
    return { pageItem, droppedLanguage: null, trimmed: false };
  }

  const translations = { ...((pageItem.aiMeta || {}).translations || {}) };
  const keep = translations[requestedLanguage] ? requestedLanguage : "en";
  let droppedLanguage = null;

  for (const code of Object.keys(translations)) {
    if (code !== keep) {
      delete translations[code];
      droppedLanguage = code;
    }
  }
  let out = { ...pageItem, aiMeta: { ...pageItem.aiMeta, translations, activeLanguage: keep } };
  if (byteLength(out) <= limit) return { pageItem: out, droppedLanguage, trimmed: false };

  // Still too big: give up sections of the surviving copy, one entry at
  // a time, so a note that is barely over loses almost nothing.
  const content = { ...translations[keep] };
  let trimmed = false;
  for (const field of TRIM_ORDER) {
    while (Array.isArray(content[field]) && content[field].length > 0 && byteLength(out) > limit) {
      content[field] = content[field].slice(0, -1);
      trimmed = true;
      out = { ...out, aiMeta: { ...out.aiMeta, translations: { [keep]: content } } };
    }
  }
  // The overview is last, and is shortened rather than removed -- a note
  // with no overview isn't a note.
  if (byteLength(out) > limit && typeof content.overview === "string") {
    const over = byteLength(out) - limit;
    content.overview = content.overview.slice(0, Math.max(200, content.overview.length - over - 200));
    trimmed = true;
    out = { ...out, aiMeta: { ...out.aiMeta, translations: { [keep]: content } } };
  }
  return { pageItem: out, droppedLanguage, trimmed };
}

function formatBody({ overview, keyPoints, assessable, openQuestions }) {
  const parts = [overview || ""];
  if (keyPoints && keyPoints.length) {
    parts.push("", "Key points:", ...keyPoints.map((p) => `• ${p}`));
  }
  if (assessable && assessable.length) {
    parts.push("", "Might be assessed:", ...assessable.map((p) => `• ${p}`));
  }
  if (openQuestions && openQuestions.length) {
    parts.push("", "Open questions:", ...openQuestions.map((p) => `• ${p}`));
  }
  return parts.join("\n");
}

/* ---------- how many study cards one lecture makes ----------

   Every term used to become a card, automatically. A lecture yields
   8-15, cards are ~150 bytes each and live in the blob forever, and a
   student attending 24 lectures a semester was silently handed 240-360
   cards they never chose -- the largest single collection in the planner
   (131KB per semester, measured) built entirely without a decision.

   The cards are now a choice made at save time, with the first six
   ticked. Six because it is a sitting's worth of review rather than a
   backlog, and because a default that is *usually right* is what stops
   this being one more screen to click through. Nothing is capped: a
   student who wants all fifteen ticks all fifteen. What changed is that
   somebody chose.

   Deliberately not a hard limit. A cap on someone's own study material
   would be the app deciding how much they are allowed to revise; the
   default decides only what happens when they don't say. */
export const DEFAULT_CARDS_SELECTED = 6;

/** The first six ticked, the rest not. */
export const defaultCardSelection = (terms = []) => (terms || []).map((_, i) => i < DEFAULT_CARDS_SELECTED);

/**
 * Pure mapper from the Edge Function's structured result to the two
 * kinds of items the app already knows how to render, sync and study.
 *
 * `selectedCards` is a boolean per term. Omitted means the default
 * selection, so a caller that doesn't care still gets sensible cards
 * rather than none. An array of all-false is a DECISION -- the student
 * unticked everything -- and must not be read as "nothing supplied".
 */
export function mapAiResultToItems({ result, course, week, language, uid, nowISO, selectedCards }) {
  const title = `${course || "Lecture"} — Week ${week || "?"} notes`;

  if (result.summaryFailed) {
    const excerpt = truncateTranscript(result.transcript);
    const header = "Transcript (AI summary failed — you can re-run summarizing later or edit this by hand):";
    // No aiMeta on this page, deliberately. aiMeta routes a page to the
    // AI viewer, which is read-only; this one has to open in the normal
    // editor so "edit this by hand" is actually possible.
    return {
      pageItem: {
        id: uid(),
        title,
        body: excerpt.truncated
          ? `${header}\n\n${excerpt.text}\n\n[Only the first ${excerpt.text.length.toLocaleString()} characters are saved here, of ${excerpt.fullLength.toLocaleString()}. Download the full transcript from the recording screen before you leave it — it isn't kept afterwards.]`
          : `${header}\n\n${excerpt.text}`,
        html: "",
        strokes: [],
        style: "lined",
        kind: "text",
        font: "sans",
        folderId: null,
      },
      noteItems: [],
    };
  }

  const selection = Array.isArray(selectedCards) ? selectedCards : defaultCardSelection(result.original.terms);

  const translations = { en: summaryForStorage(result.original) };
  if (result.translated && language) translations[language] = summaryForStorage(result.translated);

  // The language the student asked for is the one they are most likely
  // reading, so it is what the note opens in -- and, if the cap ever
  // bites, the one that survives.
  const requested = translations[language] ? language : "en";

  const { pageItem, droppedLanguage, trimmed } = capAiNote({
    pageItem: {
      id: uid(),
      title,
      /* Deliberately empty. This used to hold formatBody(result.original),
         a rendering of content that aiMeta already stores verbatim --
         the same summary twice, ~30% of the note. AiLectureNoteView
         renders from aiMeta.translations; NoteRow previews from it too.
         `body` stays as a key so notes saved before this change, which
         DO have one, keep working: readers fall back to it. */
      body: "",
      html: "",
      strokes: [],
      style: "lined",
      kind: "text",
      font: "sans",
      folderId: null,
      aiMeta: {
        course,
        week,
        generatedAt: nowISO(),
        activeLanguage: requested,
        translations,
      },
    },
    requestedLanguage: requested,
  });

  if (droppedLanguage || trimmed) {
    pageItem.aiMeta.capped = { droppedLanguage: droppedLanguage || null, trimmed };
  }

  return {
    pageItem,
    // Study cards come from the ORIGINAL terms even when a translation
    // was requested: the Study tab has one card list per semester and no
    // notion of language, so mixing languages into it would produce a
    // deck the student can't filter.
    noteItems: (result.original.terms || [])
      .filter((_, i) => (selection ? selection[i] : true))
      .map((t) => ({
        id: uid(),
        course,
        week,
        term: t.term,
        content: t.content,
      })),
  };
}

/* ---------- recordings file themselves ----------

   A recorded note lands in a folder named for its course, so a student
   with six subjects doesn't get one flat list of forty lectures.

   ONE FOLDER PER COURSE, not one per lecture and not one each for
   lectures and tutorials. Splitting those is more structure than most
   students want, and the week is already on the note.

   FIND OR CREATE, never duplicate: matched case-insensitively on the
   trimmed name, because "BIOL1010" and "biol1010 " are the same course
   to everyone except a string comparison.

   Recreating a folder the student deleted is accepted rather than
   guarded against. The alternative is remembering that they deleted it
   -- a tombstone consulted on every save, which is state that has to
   sync and can disagree between devices, to prevent something a student
   fixes by dragging one note. Deleting a folder in this app doesn't
   delete its notes either, so the folder is a view, not a container. */

/** `null` course means no folder at all — see folderForRecording. */
export const recordingFolderName = (course) => `${String(course || "").trim()} recordings`;

/**
 * The folder a new recording belongs in, creating one if needed.
 *
 * NO COURSE MEANS NO FOLDER, deliberately. A catch-all "Recordings"
 * folder would add a permanent entry to the sidebar that groups nothing
 * -- every uncoursed recording in one pile is exactly the notes list
 * again -- and sitting beside "BIOL1010 recordings" it reads as a bug
 * rather than a category. The note still saves, still appears in the
 * list, and the student can file it themselves with the move control
 * that already exists. Inventing a placeholder course name would be
 * worse: it would put a course in their planner that they never typed.
 */
export function folderForRecording({ folders = [], course, uid, nowISO }) {
  const name = String(course || "").trim();
  if (!name) return { folderId: null, newFolder: null };

  const wanted = recordingFolderName(name).toLowerCase();
  const existing = (folders || []).find(
    (f) => f && !f.deletedAt && String(f.name || "").trim().toLowerCase() === wanted
  );
  if (existing) return { folderId: existing.id, newFolder: null };

  const folder = { id: uid(), name: recordingFolderName(name), color: "stone", updatedAt: nowISO() };
  return { folderId: folder.id, newFolder: folder };
}

/** A short preview for the notes list, now that AI notes carry no body. */
export function aiNotePreview(page, limit = 200) {
  if (!page) return "";
  const meta = page.aiMeta;
  if (!meta || !meta.translations) return page.body || "";
  const content = meta.translations[meta.activeLanguage] || meta.translations.en;
  const overview = (content && content.overview) || "";
  if (!overview) return page.body || "";
  return overview.length > limit ? `${overview.slice(0, limit).trimEnd()}…` : overview;
}

/* ---------- recovering a result the app lost the address of ----------

   The Edge Function stores the whole result -- transcript, summary and
   translation -- in ai_notes_requests, keyed by (user_id,
   idempotency_key), and the scoped lookup returns it for a completed
   row. So a failed or interrupted recording is NOT lost on reload. What
   was lost was the client's memory of the key: it lived in the recorder
   reducer and went with the component.

   36 bytes in the synced blob fixes that, and syncing it (rather than
   keeping it in localStorage) is what makes recovery work on the OTHER
   device -- localStorage is per-origin, per-device, so a key kept there
   could never reach the phone that didn't do the recording.

   Note the null rather than a delete in clearPendingRecovery: mergeData
   spreads local.meta then newer.meta, so a key simply removed on one
   device would be reinstated by the other's copy. An explicit null is
   what propagates a clear. */
export function setPendingRecovery(meta, { key, course, week, startedAt }) {
  return { ...(meta || {}), pendingAiRecovery: { key, course: course || "", week: week || "", startedAt } };
}

export function clearPendingRecovery(meta) {
  return { ...(meta || {}), pendingAiRecovery: null };
}

export function pendingRecovery(meta) {
  const p = meta && meta.pendingAiRecovery;
  return p && p.key ? p : null;
}

/* ---------- recording state machine ----------

   idle -> requesting -> recording <-> paused -> stopped -> uploading -> review -> saving -> done
                  \-> error (mic denied, blob never existed)
                                            uploading/saving -> error (blob PRESERVED — retry doesn't lose the recording)

   `blob` is only ever cleared by "discard" or "saved" — every error/
   retry transition leaves it untouched, which is what makes "a failed
   transcription doesn't lose the user's recording" a property of the
   reducer rather than a manual QA claim.
------------------------------------------------------------------- */

export const INITIAL_RECORDER_STATE = {
  status: "idle",
  blob: null,
  mimeType: null,
  idempotencyKey: null,
  estimatedDurationSeconds: 0,
  path: null,
  result: null,
  errorCode: null,
  errorMessage: null,
};

export function recorderReducer(state, action) {
  switch (action.type) {
    case "request":
      return { ...state, status: "requesting", errorMessage: null, errorCode: null };

    case "requestDenied":
      return {
        ...INITIAL_RECORDER_STATE,
        status: "error",
        errorMessage: action.message,
      };

    case "started":
      return { ...state, status: "recording" };

    case "pause":
      return state.status === "recording" ? { ...state, status: "paused" } : state;

    case "resume":
      return state.status === "paused" ? { ...state, status: "recording" } : state;

    case "stop":
      // idempotencyKey is minted once here and stays stable across every
      // retry of *this* recording, so a client retry after a timeout
      // reuses the same key instead of risking a double-billed duplicate.
      return {
        ...state,
        status: "stopped",
        blob: action.blob,
        mimeType: action.mimeType,
        idempotencyKey: action.idempotencyKey,
        estimatedDurationSeconds: action.estimatedDurationSeconds,
      };

    case "discard":
      return { ...INITIAL_RECORDER_STATE };

    case "upload":
      return state.blob ? { ...state, status: "uploading", errorMessage: null, errorCode: null } : state;

    case "uploaded":
      return { ...state, status: "uploading", path: action.path };

    case "uploadFailed":
      return { ...state, status: "error", errorCode: action.code, errorMessage: action.message };

    case "processed":
      return { ...state, status: "review", result: action.result };

    case "retry":
      // Only meaningful from "error", and only if there's still a blob
      // to retry with — otherwise there's nothing to do but discard.
      return state.blob ? { ...state, status: "uploading", errorMessage: null, errorCode: null } : state;

    case "save":
      return { ...state, status: "saving" };

    case "saveFailed":
      return { ...state, status: "review", errorMessage: action.message };

    case "saved":
      return { ...INITIAL_RECORDER_STATE, status: "done" };

    case "reset":
      return { ...INITIAL_RECORDER_STATE };

    default:
      return state;
  }
}
